services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $backendActions: !tagged_locator { tag: forkcms.backend.action }
      $backendAjaxActions: !tagged_locator { tag: forkcms.backend.ajax_action }
      $backendDashboardWidgets: !tagged_locator { tag: forkcms.backend.widget }

  ForkCMS\Modules\Backend\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\Backend\DependencyInjection\BackendRouteLoader:
    arguments:
      - '@routing.loader.yml'

  ForkCMS\Modules\Backend\Backend\Actions\:
    resource: '../Backend/Actions/*'

  ForkCMS\Modules\Backend\Backend\Ajax\:
    resource: '../Backend/Ajax/*'

  ForkCMS\Modules\Backend\Backend\Widgets\:
    resource: '../Backend/Widgets/*'

  ForkCMS\Modules\Backend\Backend\Actions\NotFound:
    public: true

  ForkCMS\Modules\Backend\Console\:
    resource: '../Console/*'

  ForkCMS\Modules\Backend\Domain\Authentication\TwoFactorAuthenticationFactory:
    public: true
