services:
    form.handler.copy_widgets_to_other_locale:
        class: Backend\Modules\FormBuilder\Command\CopyFormWidgetsToOtherLocaleHandler
        public: true
        arguments:
            - "@database"
        tags:
            - { name: command_handler, handles: Backend\Modules\FormBuilder\Command\CopyFormWidgetsToOtherLocale }
