services:
    formbuilder.submitted.mailer:
        class: Frontend\Modules\FormBuilder\EventListener\FormBuilderSubmittedMailSubscriber
        arguments:
            - "@mailer"
        tags:
            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
    formbuilder.submitted.notifier:
        class: Frontend\Modules\FormBuilder\EventListener\FormBuilderSubmittedNotificationSubscriber
        tags:
            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
