services:
    formbuilder.submitted.mailer:
        class: App\Frontend\Modules\FormBuilder\EventListener\FormBuilderSubmittedMailSubscriber
        arguments:
            - "@mailer"
            - "@fork.settings"
        tags:
            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
