services:
    content_blocks.repository.content_block:
        class: Backend\Modules\ContentBlocks\Domain\ContentBlock\ContentBlockRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\ContentBlocks\Domain\ContentBlock\ContentBlock
