imports:
  - { resource: commands.yml }
  - { resource: repositories.yml }

services:
    content_blocks.copy:
        class: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocale
        tags:
            - { name: forkcms.copy_module_content_to_other_locale }
