liip_imagine:
    resolvers:
       default:
          web_path:
            web_root: "%kernel.project_dir%/"
            cache_prefix: src/Frontend/Files/Cache
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/"
                locator: filesystem_insecure
    cache: default
    data_loader: default

    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"

    # define your filter sets under this option
    filter_sets:
        # the name of the "filter set"
        media_library_backend_thumbnail:
            # adjust the image quality to 95%
            quality: 95
            # list of transformations to apply (the "filters")
            filters:
                ## Using the "thumbnail + background" combination will crop the
                ## the centered image to create your required width/height.
                # Use the "outbound" mode to crop the image when the size ratio of the input differs
                thumbnail: { size : [140, 90], mode : outbound }
                background: { size : [140, 90], position : center }
        media_library_lightbox_small:
            filters:
                scale: { dim : [800, 600] }
        media_library_lightbox_large:
            filters:
                scale: { dim : [1600, 800] }
        media_library_slider_pano:
            filters:
                scale: { dim : [1600, 600] }
        media_library_one_image_large:
            filters:
                thumbnail: { size : [1600, 500], mode : inbound }