# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    google:
        enabled: true
        template: '@Backend\Backend\2fa.html.twig'


    trusted_device:
        enabled: true
        extend_lifetime: true
        key: cc21ed8d4b2a28a1f14028428fd3b5e5scheb
