twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
      '%site.path_www%/src/Frontend/Modules/': ForkFrontendModules
      '%kernel.project_dir%/templates/installer': installer
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "%fork.form.theme%"