twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
      '%kernel.project_dir%/src/Frontend/Modules/': ForkFrontendModules
      '%kernel.project_dir%/templates/installer/': installer
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "%fork.form.theme%"