source 'https://rubygems.org'

gem 'compass'
gem 'bootstrap-sass'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'compass_sumo'
gem 'foreman'
gem 'capistrano', '~> 2.15'
gem 'sumodev_deploy'
gem 'forkcms_deploy', '>= 2.5.0'
gem 'sumodev', '~> 0.6.0'
