<?php

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function imagemanager_wysiwyg_plugin($editor, $version) {
	switch ($editor) {
		case 'tinymce':
			return array(
				'imagemanager' => array(
					'path' => drupal_get_path('module', 'imagemanager') .'/../../editor_plugin.js',
					'buttons' => array('insertimage' => t('MCImageManager')),
					'url' => 'http://wiki.moxiecode.com/index.php/MCImageManager:Index',
					'load' => TRUE
				)
			);
		break;
	}
}

function imagemanager_perm(){
	return array('access tinymce imagemanager');
}

?>