{include:{$BACKEND_CORE_PATH}/Layout/Templates/Head.tpl}
{include:{$BACKEND_CORE_PATH}/Layout/Templates/StructureStartModule.tpl}
<div class="row fork-module-heading">
  <div class="col-md-6">
    <h2>{$lblProfiles|ucfirst}: {$lblAdd}</h2>
  </div>
  <div class="col-md-6">

  </div>
</div>
{form:add}
  {option:notifyProfile}
  <p class="text-warning"><span class="fa fa-warning"></span> {$lblNewProfileWillBeNotified|ucfirst}</p>
  {/option:notifyProfile}
  <div class="row fork-module-content">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{$lblProfile|ucfirst}</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4">
              <div class="form-group{option:txtEmailError} has-error{/option:txtEmailError}">
                <label for="email" class="control-label">
                  {$lblEmail|ucfirst}
                  <abbr data-toggle="tooltip" title="{$lblRequiredField|ucfirst}">*</abbr>
                </label>
                {$txtEmail} {$txtEmailError}
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group{option:txtDisplayNameError} has-error{/option:txtDisplayNameError}">
                <label for="displayName" class="control-label">
                  {$lblDisplayName|ucfirst}
                  <abbr data-toggle="tooltip" title="{$lblRequiredField|ucfirst}">*</abbr>
                </label>
                {$txtDisplayName} {$txtDisplayNameError}
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group{option:txtPasswordError} has-error{/option:txtPasswordError}">
                <label for="password" class="control-label">
                  {$lblPassword|ucfirst}
                  {option:!notifyProfile}<abbr data-toggle="tooltip" title="{$lblRequiredField|ucfirst}">*</abbr>{/option:!notifyProfile}
                </label>
                {$txtPassword} {$txtPasswordError}
                {option:notifyProfile}<span class="helpTxt">{$msgAutoGeneratedPasswordIfEmpty}</span>{/option:notifyProfile}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row fork-module-content">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{$lblSettings|ucfirst}</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group{option:txtFirstNameError} has-error{/option:txtFirstNameError}">
                <label for="firstName" class="control-label">{$lblFirstName|ucfirst}</label>
                {$txtFirstName} {$txtFirstNameError}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group{option:txtLastNameError} has-error{/option:txtLastNameError}">
                <label for="lastName" class="control-label">{$lblLastName|ucfirst}</label>
                {$txtLastName} {$txtLastNameError}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <div class="form-group{option:ddmGenderError} has-error{/option:ddmGenderError}">
                <label for="gender" class="control-label">{$lblGender|ucfirst}</label>
                {$ddmGender} {$ddmGenderError}
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group{option:ddmYearError} has-error{/option:ddmYearError}">
                <label for="day" class="control-label">{$lblBirthDate|ucfirst}</label>
                <div class="form-inline">
                  <div class="form-group">{$ddmDay}</div>
                  <div class="form-group">{$ddmMonth}</div>
                  <div class="form-group">{$ddmYear}</div>
                  {$ddmYearError}
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group{option:txtCityError} has-error{/option:txtCityError}">
                <label for="city" class="control-label">{$lblCity|ucfirst}</label>
                {$txtCity} {$txtCityError}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group{option:ddmCountryError} has-error{/option:ddmCountryError}">
                <label for="country" class="control-label">{$lblCountry|ucfirst}</label>
                {$ddmCountry} {$ddmCountryError}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row fork-module-actions">
    <div class="col-md-12">
      <div class="btn-toolbar">
        <div class="btn-group pull-right" role="group">
          <button id="addButton" type="submit" name="add" class="btn btn-success">
            <span class="fa fa-plus"></span>&nbsp;
            {$lblAdd|ucfirst}
          </button>
        </div>
      </div>
    </div>
  </div>
{/form:add}
{include:{$BACKEND_CORE_PATH}/Layout/Templates/StructureEndModule.tpl}
{include:{$BACKEND_CORE_PATH}/Layout/Templates/Footer.tpl}
