# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: "pdo_%database.driver%"
                host: "%database.host%"
                port: "%database.port%"
                dbname: "%database.name%"
                user: "%database.user%"
                password: "%database.password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    # Remove when we don't have legacy tables anymore
                    enum: string
        types:
            seo_follow: Common\Doctrine\Type\SEOFollowType
            seo_index: Common\Doctrine\Type\SEOIndexType
            locale: Common\Doctrine\Type\LocaleType
            datetime: Common\Doctrine\Type\UTCDateTimeType
            datetimetz: Common\Doctrine\Type\UTCDateTimeType
            time: Common\Doctrine\Type\UTCTimeType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    common:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Common/Doctrine/Entity"
                        alias: Common
                        prefix: Common\Doctrine\Entity
                dql:
                    numeric_functions:
                        ceil: DoctrineExtensions\Query\Mysql\Ceil
                        unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
                        least: DoctrineExtensions\Query\Mysql\Least
                    string_functions:
                        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                        ifelse: DoctrineExtensions\Query\Mysql\IfElse

doctrine_orm_bridge:
    entity_manager: default
    connection: default

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Common\Doctrine\Entity\CreateSchema:

    Common\Doctrine\Repository\MetaRepository:
