parameters:
    fork.form.theme: 'Core/Layout/Templates/FormLayout.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Common\Form\DatePickerType:
        tags:
          - { name: form.type }

    Backend\Form\Type\EditorType:
        tags:
            - { name: form.type, alias: editor}

    Backend\Form\Type\MetaType:
        tags:
            - { name: form.type, alias: meta}

    Common\Form\ImageType:
        tags:
            - { name: form.type, alias: image}

    Common\Form\FileType:
        tags:
            - { name: form.type, alias: file}

    Common\Form\Extension\DateTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
