services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Profiles\Domain\Profile\ProfileRepository:

    Backend\Modules\Profiles\Domain\Setting\SettingRepository:

    Backend\Modules\Profiles\Domain\Group\GroupRepository:

    Backend\Modules\Profiles\Domain\GroupRight\GroupRightRepository:

    Backend\Modules\Profiles\Domain\Session\SessionRepository:
