#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__ . '/../autoload.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Common\Tool\Command\ClearCache;
use Common\Tool\Command\PrepareForReinstall;

$input = new ArgvInput();
$kernel = new AppKernel();
$application = new Application($kernel);

// add custom commands
$application->add(new ClearCache);
$application->add(new PrepareForReinstall);

// run the application
$application->run($input);
