services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Blog\Domain\Comment\CommentRepository:

    Backend\Modules\Blog\Domain\Category\CategoryRepository:
