// Generated by CoffeeScript 1.6.3
(function() {
  var DefaultTheme, SpecificTheme, Theme, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Theme = (function() {
    Theme.events = function(events) {
      var _base;
      if ((_base = this.prototype).events == null) {
        _base.events = {};
      }
      if (!this.prototype.hasOwnProperty("events")) {
        this.prototype.events = $.extend({}, this.prototype.events);
      }
      return this.prototype.events = $.extend(true, {}, this.prototype.events, events);
    };

    Theme.onDomReady = function(initializers) {
      var initializer, _base, _i, _len, _results;
      if ((_base = this.prototype).onDomReady == null) {
        _base.onDomReady = [];
      }
      if (!this.prototype.hasOwnProperty("onDomReady")) {
        this.prototype.onDomReady = this.prototype.onDomReady.slice(0);
      }
      _results = [];
      for (_i = 0, _len = initializers.length; _i < _len; _i++) {
        initializer = initializers[_i];
        _results.push(this.prototype.onDomReady.push(initializer));
      }
      return _results;
    };

    function Theme() {
      this._setupEventListeners = __bind(this._setupEventListeners, this);
      this._setupEventListeners();
    }

    Theme.prototype.domReady = function() {
      return this._loadOnDomReadyMethods();
    };

    Theme.prototype._loadOnDomReadyMethods = function() {
      var callback, _i, _len, _ref, _results;
      _ref = this.onDomReady;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        callback = _ref[_i];
        _results.push(this[callback]());
      }
      return _results;
    };

    Theme.prototype._setupEventListeners = function() {
      var $document, action, actions, callback, selector, _ref, _results;
      $document = $(document);
      _ref = this.events;
      _results = [];
      for (selector in _ref) {
        actions = _ref[selector];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (action in actions) {
            callback = actions[action];
            _results1.push($document.on(action, selector, this[callback]));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Theme;

  })();

  DefaultTheme = (function(_super) {
    __extends(DefaultTheme, _super);

    function DefaultTheme() {
      this.scrollTo = __bind(this.scrollTo, this);
      _ref = DefaultTheme.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    DefaultTheme.events({
      '#cookieBar .close': {
        click: 'cookieBarHide'
      },
      '#cookieBarAgree': {
        click: 'cookieBarAgree'
      },
      '#cookieBarDisagree': {
        click: 'cookieBarDisagree'
      },
      'input:submit': {
        click: 'hijackSubmit'
      },
      'a.backToTop': {
        click: 'scrollToTop'
      },
      'a[href*="#"]': {
        click: 'scrollTo'
      }
    });

    DefaultTheme.onDomReady(['cookieBar', 'removeImageHeight', 'initCarouselWithSwipe']);

    DefaultTheme.prototype.cookieBar = function() {
      if (utils.cookies.readCookie('cookie_bar_hide') === 'b%3A1%3B') {
        return $('#cookieBar').remove();
      }
    };

    DefaultTheme.prototype.cookieBarAgree = function() {
      utils.cookies.setCookie('cookie_bar_agree', 'b:1;');
      utils.cookies.setCookie('cookie_bar_hide', 'b:1;');
      $('#cookieBar').alert('close');
      if (typeof _gaq !== "undefined" && _gaq !== null) {
        _gaq.push(['_trackEvent', 'cookiebar', 'agree']);
      }
      return false;
    };

    DefaultTheme.prototype.cookieBarDisagree = function() {
      utils.cookies.setCookie('cookie_bar_agree', 'b:0;');
      utils.cookies.setCookie('cookie_bar_hide', 'b:1;');
      $('#cookieBar').alert('close');
      if (typeof _gaq !== "undefined" && _gaq !== null) {
        _gaq.push(['_trackEvent', 'cookiebar', 'disagree']);
      }
      return false;
    };

    DefaultTheme.prototype.cookieBarHide = function() {
      if (typeof _gaq !== "undefined" && _gaq !== null) {
        _gaq.push(['_trackEvent', 'cookiebar', 'hide']);
      }
      return false;
    };

    DefaultTheme.prototype.hijackSubmit = function(e) {
      return $(this).addClass('loading');
    };

    DefaultTheme.prototype.scrollToTop = function(e) {
      $('html, body').stop().animate({
        scrollTop: 0
      }, 600);
      return false;
    };

    DefaultTheme.prototype.scrollTo = function(e) {
      var $anchor, hash, href, url,
        _this = this;
      $anchor = $(e.currentTarget);
      href = $anchor.attr('href');
      url = href.substr(0, href.indexOf('#'));
      hash = href.substr(href.indexOf('#'));
      if ((url === '' || url.indexOf(document.location.pathname) >= 0) && !$anchor.is('[data-no-scroll]') && $(hash).length > 0) {
        $('html, body').stop().animate({
          scrollTop: $(hash).offset().top
        }, 600, function() {
          return _this.setFocus(hash);
        });
        return false;
      }
    };

    DefaultTheme.prototype.removeImageHeight = function() {
      return $('img').css({
        height: 'auto'
      }).addClass('img-responsive');
    };

    DefaultTheme.prototype.initCarouselWithSwipe = function() {
      $('.carousel').on('swipeleft', function(e) {
        return $(e.currentTarget).carousel('next');
      });
      return $('.carousel').on('swiperight', function(e) {
        return $(e.currentTarget).carousel('prev');
      });
    };

    DefaultTheme.prototype.setFocus = function(hash) {
      if ($(hash).find('.nonVisibleAnchor').length > 0) {
        return $(hash).find('.nonVisibleAnchor').focus();
      } else {
        return false;
      }
    };

    return DefaultTheme;

  })(Theme);

  SpecificTheme = (function(_super) {
    __extends(SpecificTheme, _super);

    function SpecificTheme() {
      _ref1 = SpecificTheme.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    SpecificTheme.events;

    SpecificTheme.onDomReady([]);

    window.requestAnimationFrame = (function() {
      var lastTime;
      lastTime = 0;
      return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
        var curTime, id, timeToCall;
        curTime = new Date().getTime();
        timeToCall = Math.max(0, 16 - (curTime - lastTime));
        id = window.setTimeout(function() {
          return callback(curTime + timeToCall);
        }, timeToCall);
        lastTime = curTime + timeToCall;
        return id;
      };
    })();

    return SpecificTheme;

  })(DefaultTheme);

  SpecificTheme.current = new SpecificTheme();

  $(function() {
    return SpecificTheme.current.domReady();
  });

  window.SpecificTheme = SpecificTheme;

}).call(this);
