services:
    fork.validator.url:
        class: ForkCMS\Bundle\CoreBundle\Validator\UrlValidator
        public: true

    ForkCMS\Bundle\CoreBundle\Validator\UniqueDataTransferObjectValidator:
        public: true
        autowire: true
        tags:
            - { name: validator.constraint_validator, alias: unique_data_transfer_object }
