services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    fork.validator.url:
        class: ForkCMS\Bundle\CoreBundle\Validator\UrlValidator

    ForkCMS\Bundle\CoreBundle\Validator\UniqueDataTransferObjectValidator:
        tags:
            - { name: validator.constraint_validator, alias: unique_data_transfer_object }

