services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $twigBridgeRoutingExcension: '@twig.extension.routing'
      $editorTypeImplementations: !tagged_locator { tag: 'forkcms.editor' }

  _instanceof:
    Symfony\Component\Console\Command\Command:
      bind:
        string $rootDir: '%kernel.project_dir%'
        bool $forkIsInstalled: '%fork.is_installed%'
    Symfony\Bundle\MakerBundle\MakerInterface:
      tags:
        - { name: maker.command }

  ForkCMS\Core\Domain\:
    resource: '../Domain/*'
    exclude:
      - '../Domain/PDO'
      - '../Domain/Kernel/Kernel.php'

  ForkCMS\Core\Domain\Settings\SettingsListener:
    tags:
      - { name: doctrine.event_listener, event: preFlush }

  ForkCMS\Core\Domain\Router\ModuleRouteLoader:
    arguments:
      - !tagged_iterator { tag: forkcms.routing.loader }
    tags:
      - { name: routing.loader }

  ForkCMS\Core\DependencyInjection\CoreRouteLoader:
    arguments:
      - '@routing.loader.yml'

  Twig\Extension\StringLoaderExtension:

  ForkCMS\Core\Controller\:
    resource: '../Controller/*'
    public: true
