<?php

/**
 * This file is generated by the Backend, it contains
 * more information about the page-structure
 * 
 * @author	Backend
 * @generated	2009-11-04 16:49:36
 */

$navigation['root'][0][1]['page_id'] = 1;
$navigation['root'][0][1]['url'] = 'url';
$navigation['root'][0][1]['full_url'] = 'url';
$navigation['root'][0][1]['title'] = 'title';
$navigation['root'][0][1]['navigation_title'] = 'navigation_title';

$navigation['page'][0][4]['page_id'] = 4;
$navigation['page'][0][4]['url'] = 'test';
$navigation['page'][0][4]['full_url'] = 'test';
$navigation['page'][0][4]['title'] = 'Test';
$navigation['page'][0][4]['navigation_title'] = '';

$navigation['page'][1][2]['page_id'] = 2;
$navigation['page'][1][2]['url'] = 'url';
$navigation['page'][1][2]['full_url'] = 'url/url';
$navigation['page'][1][2]['title'] = 'title';
$navigation['page'][1][2]['navigation_title'] = 'navigation_title';

$navigation['page'][1][3]['page_id'] = 3;
$navigation['page'][1][3]['url'] = 'url';
$navigation['page'][1][3]['full_url'] = 'url/url';
$navigation['page'][1][3]['title'] = 'you suck';
$navigation['page'][1][3]['navigation_title'] = 'sucker';

?>