services:
  forkcms.console.cache.clear:
    class: App\Console\Core\CacheClearCommand
    tags:
      - { name: console.command }

  forkcms.console.installer.prepare_for_reinstall:
    class: App\Console\Installer\PrepareForReinstallCommand
    tags:
      - { name: console.command }

  forkcms.console.installer.check_requirements:
    class: App\Console\Installer\CheckRequirementsCommand
    tags:
      - { name: console.command }
    arguments: ['@forkcms.requirements.checker']
