parameters:
    fork.form.theme: 'Core/Layout/Templates/FormLayout.html.twig'
    fork.form.default_preferred_editor: 'ck-editor'
    fork.form.available_editors:
        ck-editor: 'CK Editor'
        html: 'HTML'

services:
    fork.datepicker.form:
        class: App\Common\Form\DatePickerType
        arguments:
          - "@service_container"
        tags:
          - { name: form.type }
    form.type.editor:
        class: App\Backend\Form\Type\EditorType
        tags:
            - { name: form.type, alias: editor}
    form.type.meta:
        class: App\Backend\Form\Type\MetaType
        arguments:
            - "@fork.repository.meta"
            - "@translator"
        tags:
            - { name: form.type, alias: meta}
