parameters:
    database.driver:        mysql
    database.host:          127.0.0.1
    database.port:          3306
    database.name:          jeroendesloovere-symfony-4
    database.user:          root
    database.password:      root

    kernel.secret:          <secret>

    fork.debug_email:       <debug-email>
    fork.debug_message:     'Internal error.'
    fork.version:           '5.2.2'

    site.protocol:          http
    site.domain:            test.jeroendesloovere-symfony-4.test
    site.default_title:     <site-default-title>
    site.multilanguage:     <site-multilanguage>
    site.default_language:  nl
    site.path_www:          "%kernel.project_dir%"

    action.group_tag:       '<action-group-tag>'
    action.rights_level:    <action-rights-level>