install_step1:
    path: /install/1
    controller: App\Controller\InstallerController::step1Action
install_step2:
    path: /install/2
    controller: App\Controller\InstallerController::step2Action
install_step3:
    path: /install/3
    controller: App\Controller\InstallerController::step3Action
install_step4:
    path: /install/4
    controller: App\Controller\InstallerController::step4Action
install_step5:
    path: /install/5
    controller: App\Controller\InstallerController::step5Action
install_step6:
    path: /install/6
    controller: App\Controller\InstallerController::step6Action
install:
    path: /install
    controller: App\Controller\InstallerController::noStepAction

# default routes
_main:
    resource: routes.yaml
