imports:
    - { resource: console.yaml }
    - { resource: form.yaml }
    - { resource: parameters.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    fork.is_installed: true
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    ForkCMS\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    ForkCMS\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser:
        public: true
    Symfony\Component\Config\FileLocator:
        public: true
    Psr\Log\LoggerInterface:
        public: true
    SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware:
        public: true
    command_bus.public:
        alias: command_bus
        public: true
    # @todo: enable this again when liip/imagine-bundle:^2.0 is released (which supports symfony 4)
    #Liip\ImagineBundle\Imagine\Cache\CacheManager:
    #    public: true
    MailMotor\Bundle\MailMotorBundle\Factory\MailMotorFactory:
        public: true
        autowire: false
    database:
        class: SpoonDatabase
        public: true
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%"
            - "%database.port%"
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
            # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
            # and caused some queries to break.
            - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")'] ]
            - [ setDebug, [ "%kernel.debug%" ]]
    mailer_configurator:
        class: ForkCMS\Common\Mailer\Configurator
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
        arguments:
            - "@fork.settings"
            - "@service_container"

    cache.filesystem.adapter:
        class: League\Flysystem\Adapter\Local
        arguments:
            - "%kernel.cache_dir%"
    cache.filesystem.filesystem:
        class: League\Flysystem\Filesystem
        arguments:
            - "@cache.filesystem.adapter"
    cache.adapter:
        class: MatthiasMullie\Scrapbook\Adapters\Flysystem
        arguments:
            - "@cache.filesystem.filesystem"
    cache.buffer:
        class: MatthiasMullie\Scrapbook\Buffered\BufferedStore
        arguments:
            - "@cache.adapter"
    cache.pool:
        class: MatthiasMullie\Scrapbook\Psr6\Pool
        public: true
        arguments:
            - "@cache.buffer"
    cache.backend_navigation:
        class: ForkCMS\Backend\Core\Engine\NavigationCache
        public: true
        arguments:
            - "@database"
            - "@cache.pool"

    fork.settings:
        class: ForkCMS\Common\ModulesSettings
        public: true
        arguments:
            - "@database"
            - "@cache.pool"

    fork.cookie:
        class: ForkCMS\Common\Core\Cookie
        public: true

    fork.cookie_setter:
        class: ForkCMS\Common\EventListener\ForkCookieSetter
        arguments:
            - "@fork.cookie"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    fork.response_securer:
        class: ForkCMS\Common\EventListener\ResponseSecurer
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    fork.validator.url:
        class: ForkCMS\Service\Validator\UrlValidator
        public: true

    forkcms.requirements.checker:
        class: ForkCMS\Service\Installer\RequirementsChecker
        public: true
        arguments: ['%kernel.project_dir%/']

    forkcms.installer:
        class: ForkCMS\Service\Installer\ForkInstaller
        arguments: ['@service_container']

    # Throws errors when enabling
    #templating:
    #    class: ForkCMS\Frontend\Core\Engine\TwigTemplate
    #    public: true
    #    arguments:
    #        - "@twig"
    #        - "@templating.name_parser"
    #        - "@templating.locator"

    # Throws errors when enabling
    #translator:
    #    class: ForkCMS\Common\Language
    #    public: true
    #    arguments:
    #        - "@translator.selector"
