imports:
    - { resource: services_dev.yaml }

parameters:
    site.multilanguage: true

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.project_dir%/config/routes_install.yaml"

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        connections:
            default:
                dbname: "%database.name%_test"

services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.ForkCMS\Utility\MyService: '@ForkCMS\Utility\MyService'

    database:
        class: SpoonDatabase
        public: true
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%_test"
            - "%database.port%"
        calls:
            - [ setDebug, [ "%kernel.debug%" ]]
