services:
    media_library.console.cache_clear:
        class: ForkCMS\Backend\Modules\MediaLibrary\Console\CacheClearCommand
        tags:
            -  { name: console.command }
    media_library.console.delete_media_items:
        class: ForkCMS\Backend\Modules\MediaLibrary\Console\MediaItemDeleteAllCommand
        tags:
            -  { name: console.command }
