services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Frontend helpers
    media_library.helper.frontend:
        class: Frontend\Modules\MediaLibrary\Helper\FrontendHelper
