services:
    media_galleries.console.delete_galleries:
        class: ForkCMS\Backend\Modules\MediaGalleries\Console\MediaGalleryDeleteAllCommand
        tags:
            - { name: console.command }
