services:
    media_galleries.repository.gallery:
        class: Backend\Modules\MediaGalleries\Domain\MediaGallery\MediaGalleryRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\MediaGalleries\Domain\MediaGallery\MediaGallery
