(function(){function b(a){test.mode(a,g,Array.prototype.slice.call(arguments,1))}function f(a,b,c){b=[b];for(var d=1;d<=c;++d)b[d]=a.join(b[d-1]);return b}var g=CodeMirror.getMode({indentUnit:2},"php");b("simple_test",'[meta \x3c?php] [keyword echo] [string "aaa"]; [meta ?\x3e]');b("variable_interpolation_non_alphanumeric","[meta \x3c?php]",'[keyword echo] [string "aaa$~$!$@$#$$$%$^$\x26$*$($)$.$\x3c$\x3e$/$\\$}$\\"$:$;$?$|$[[$]]$+$\x3daaa"]',"[meta ?\x3e]");b("variable_interpolation_digits","[meta \x3c?php]",
'[keyword echo] [string "aaa$1$2$3$4$5$6$7$8$9$0aaa"]',"[meta ?\x3e]");b("variable_interpolation_simple_syntax_1","[meta \x3c?php]",'[keyword echo] [string "aaa][variable-2 $aaa][string .aaa"];',"[meta ?\x3e]");b("variable_interpolation_simple_syntax_2","[meta \x3c?php]",'[keyword echo] [string "][variable-2 $aaaa][[',"[number 2]",']][string aa"];','[keyword echo] [string "][variable-2 $aaaa][[',"[number 2345]",']][string aa"];','[keyword echo] [string "][variable-2 $aaaa][[',"[number 2.3]",']][string aa"];',
'[keyword echo] [string "][variable-2 $aaaa][[',"[variable aaaaa]",']][string aa"];','[keyword echo] [string "][variable-2 $aaaa][[',"[variable-2 $aaaaa]",']][string aa"];','[keyword echo] [string "1aaa][variable-2 $aaaa][[',"[number 2]",']][string aa"];','[keyword echo] [string "aaa][variable-2 $aaaa][[',"[number 2345]",']][string aa"];','[keyword echo] [string "aaa][variable-2 $aaaa][[',"[number 2.3]",']][string aa"];','[keyword echo] [string "aaa][variable-2 $aaaa][[',"[variable aaaaa]",']][string aa"];',
'[keyword echo] [string "aaa][variable-2 $aaaa][[',"[variable-2 $aaaaa]",']][string aa"];',"[meta ?\x3e]");b("variable_interpolation_simple_syntax_3","[meta \x3c?php]",'[keyword echo] [string "aaa][variable-2 $aaaa]-\x3e[variable aaaaa][string .aaaaaa"];','[keyword echo] [string "aaa][variable-2 $aaaa][string -\x3e][variable-2 $aaaaa][string .aaaaaa"];','[keyword echo] [string "aaa][variable-2 $aaaa]-\x3e[variable aaaaa][string [[2]].aaaaaa"];','[keyword echo] [string "aaa][variable-2 $aaaa]-\x3e[variable aaaaa][string -\x3eaaaa2.aaaaaa"];',
"[meta ?\x3e]");b("variable_interpolation_escaping","[meta \x3c?php] [comment /* Escaping */]",'[keyword echo] [string "aaa\\$aaaa-\x3eaaa.aaa"];','[keyword echo] [string "aaa\\$aaaa[[2]]aaa.aaa"];','[keyword echo] [string "aaa\\$aaaa[[asd]]aaa.aaa"];','[keyword echo] [string "aaa{\\$aaaa-\x3eaaa.aaa"];','[keyword echo] [string "aaa{\\$aaaa[[2]]aaa.aaa"];','[keyword echo] [string "aaa{\\aaaaa[[asd]]aaa.aaa"];','[keyword echo] [string "aaa\\${aaaa-\x3eaaa.aaa"];','[keyword echo] [string "aaa\\${aaaa[[2]]aaa.aaa"];',
'[keyword echo] [string "aaa\\${aaaa[[asd]]aaa.aaa"];',"[meta ?\x3e]");b("variable_interpolation_complex_syntax_1","[meta \x3c?php]",'[keyword echo] [string "aaa][variable-2 $]{[variable aaaa]}[string -\x3eaaa.aaa"];','[keyword echo] [string "aaa][variable-2 $]{[variable-2 $aaaa]}[string -\x3eaaa.aaa"];','[keyword echo] [string "aaa][variable-2 $]{[variable-2 $aaaa][[',"  [number 42]",']]}[string -\x3eaaa.aaa"];','[keyword echo] [string "aaa][variable-2 $]{[variable aaaa][meta ?\x3e]aaaaaa');b("variable_interpolation_complex_syntax_2",
"[meta \x3c?php] [comment /* Monsters */]",'[keyword echo] [string "][variable-2 $]{[variable aaa][comment /*}?\x3e} $aaa\x3c?php } */]}[string -\x3eaaa.aaa"];','[keyword echo] [string "][variable-2 $]{[variable aaa][comment /*}?\x3e*/][[','  [string "aaa][variable-2 $aaa][string {}][variable-2 $]{[variable aaa]}[string "]',']]}[string -\x3eaaa.aaa"];','[keyword echo] [string "][variable-2 $]{[variable aaa][comment /*} } $aaa } */]}[string -\x3eaaa.aaa"];');var a=f(['[string "][variable-2 $]{[variable aaa] [operator +] ',
'}[string "]'],'[comment /* }?\x3e} */] [string "aaa][variable-2 $aaa][string .aaa"]',10);b("variable_interpolation_complex_syntax_3_1","[meta \x3c?php] [comment /* Recursive monsters */]","[keyword echo] "+a[4]+";","[keyword echo] "+a[7]+";","[keyword echo] "+a[8]+";","[keyword echo] "+a[5]+";","[keyword echo] "+a[1]+";","[keyword echo] "+a[6]+";","[keyword echo] "+a[9]+";","[keyword echo] "+a[0]+";","[keyword echo] "+a[10]+";","[keyword echo] "+a[2]+";","[keyword echo] "+a[3]+";",'[keyword echo] [string "end"];',
"[meta ?\x3e]");var c=f(['[string "a][variable-2 $]{[variable aaa] [operator +] '," [operator +] ",'}[string .a"]'],'[comment /* }?\x3e{{ */] [string "a?\x3e}{{aa][variable-2 $aaa][string .a}a?\x3ea"]',5);b("variable_interpolation_complex_syntax_3_2","[meta \x3c?php] [comment /* Recursive monsters 2 */]","[keyword echo] "+c[0]+";","[keyword echo] "+c[1]+";","[keyword echo] "+c[5]+";","[keyword echo] "+c[4]+";","[keyword echo] "+c[2]+";","[keyword echo] "+c[3]+";",'[keyword echo] [string "end"];',
"[meta ?\x3e]");a=function(a,b,c,d,f){d=[d];for(var e=1;e<=f;++e)d[e]=c[0]+a[e-1]+c[1]+b[e-1]+c[2]+d[e-1]+c[3];return d}(a,c,['[string "a][variable-2 $]{[variable aaa] [operator +] '," [operator +] "," [operator +] ",'}[string .a"]'],'[comment /* }?\x3e{{ */] [string "a?\x3e}{{aa][variable-2 $aaa][string .a}a?\x3ea"]',4);b("variable_interpolation_complex_syntax_3_3","[meta \x3c?php] [comment /* Recursive monsters 2 */]","[keyword echo] "+a[4]+";","[keyword echo] "+a[0]+";","[keyword echo] "+a[3]+
";","[keyword echo] "+a[1]+";","[keyword echo] "+a[2]+";",'[keyword echo] [string "end"];',"[meta ?\x3e]");b("variable_interpolation_heredoc","[meta \x3c?php]","[string \x3c\x3c\x3chere]","[string doc ][variable-2 $]{[variable yay]}[string more]","[string here]; [comment // normal]")})();