#! /bin/bash
# Script to remove all cache files
# Useful when merging two Fork installs
# Run from the scripts/ folder
rm ../../../default_www/install/cache/*
rm ../../../default_www/frontend/cache/cached_templates/*
rm ../../../default_www/frontend/cache/locale/*
rm ../../../default_www/frontend/cache/minified_css/*
rm ../../../default_www/frontend/cache/minified_js/*
rm ../../../default_www/frontend/cache/navigation/*
rm ../../../default_www/frontend/cache/statistics/*
rm ../../../default_www/frontend/cache/templates/*
rm ../../../default_www/backend/cache/analytics/*
rm ../../../default_www/backend/cache/cronjobs/*
rm ../../../default_www/backend/cache/locale/*
rm ../../../default_www/backend/cache/templates/*
echo 'All done! Cache files removed.'