#!/bin/bash
#
# This script will check if your code matches the guidelines
#
# @version	2.0.0

# determine the relevant directories
base_dir="$(dirname "$0")/..";

# run it
bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 --ignore=src/Backend/Core/Js/ckfinder,src/Backend/Cache,src/Frontend/Cache,src/Backend/Core/Js/ckeditor --report=full "${@:-src}"
