#!/bin/bash
#
# Open a MySQL connection using the parameters.yml file.
#
# @author Jan Moesen
# @author Dieter Vanden Eynde <dieter.vandeneynde@wijs.be>


cd "$(dirname "$0")";

# "Parse" the YAML file for the given parameter.
function extract_from_yml {
    local parameter="$1";
    while read -r line; do
        if ! [[ "$line" =~ ^[[:space:]]*([^[:space:]:]*)[[:space:]]*:[[:space:]]*([^[:space:]]*) ]]; then
            continue;
        fi;

        local curr_parameter="${BASH_REMATCH[1]}";
        local curr_value="${BASH_REMATCH[2]}";
        if [ "$curr_parameter" = "$parameter" ]; then
            echo "$curr_value";
            return;
        fi;
    done < ../app/config/parameters.yml;
    return 1;
}

db_host="$(extract_from_yml database.host || echo 127.0.0.1)";
db_port="$(extract_from_yml database.port || echo 3306)";
[ "$db_port" = '~' ] && db_port=3306;
db_name="$(extract_from_yml database.name)";
db_user="$(extract_from_yml database.user)";
db_pass="$(extract_from_yml database.password)";

if [[ "$db_pass" == "null" ]]; then
    db_pass="";
fi;

exec mysql --default-character-set='utf8' --host="$db_host" --port="$db_port" --user="$db_user" --password="$db_pass" --database="$db_name" "$@";
