#! /bin/bash
#
# This script will minify stuff, should be run before creating a release.
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

function check {
	# check for YUI compressor
	if [ ! -f ./library/yuicompressor.jar ]; then
		echo "Can't find YUI-compressor!"
		exit 1
	fi
}

function minifyJS {
	echo "* Creating temporary JS-file"

	# remove temp file
	rm -f ./minified.tmp.js
	
	cat ../backend/core/js/jquery/jquery.js >> minified.tmp.js
	echo -e "\n" >> minified.tmp.js
	cat ../backend/core/js/jquery/jquery.ui.js >> minified.tmp.js
	cat ../backend/core/js/jquery/jquery.ui.dialog.patch.js >> minified.tmp.js
	echo -e "\n" >> minified.tmp.js
	cat ../backend/core/js/jquery/jquery.tools.js >> minified.tmp.js
	echo -e "\n" >> minified.tmp.js
	cat ../backend/core/js/jquery/jquery.backend.js >> minified.tmp.js
	echo -e "\n" >> minified.tmp.js
	java -jar ./library/yuicompressor.jar --type js --charset utf8 --nomunge --preserve-semi ../backend/core/js/jquery/jquery.backend.js >> minified.tmp.js
	
	echo "* Combined jQuery files and minified our Fork-plugin"
	
	# move to correct location
	mv -f ./minified.tmp.js ../backend/core/js/minified.js
	
	# tell user
	echo "* Saved minified jQuery-javascript and removed temporary JS-file"
}

# do checks
check

# minify JS
minifyJS

# done
echo "Done"