#!/bin/bash
#
# This is a simple script to easily update the current database with a given file.sql.
#
# @author Jelmer Snoeck <jelmer.snoeck@wijs.be>
# @author Per Juchtmans <per.juchtmans@wijs.be>
# @author Dieter Vanden Eynde <dieter.vandeneynde@wijs.be>

cd "$(dirname "$0")";

# "Parse" the YAML file for the given parameter.
function extract_from_yml {
    local parameter="$1";
    while read -r line; do
        if ! [[ "$line" =~ ^[[:space:]]*([^[:space:]:]*)[[:space:]]*:[[:space:]]*([^[:space:]]*) ]]; then
            continue;
        fi;

        local curr_parameter="${BASH_REMATCH[1]}";
        local curr_value="${BASH_REMATCH[2]}";
        if [ "$curr_parameter" = "$parameter" ]; then
            echo "$curr_value";
            return;
        fi;
    done < ../app/config/parameters.yml;
    return 1;
}

db_host="$(extract_from_yml database.host || echo 127.0.0.1)";
db_port="$(extract_from_yml database.port || echo 3306)";
[ "$db_port" = '~' ] && db_port=3306;
db_name="$(extract_from_yml database.name)";
db_user="$(extract_from_yml database.user)";
db_pass="$(extract_from_yml database.password)";

if [[ "$db_pass" == "null" ]]; then
    db_pass="";
fi;

MYSQL="$(which mysql)"
UPDATE_PATH=$1

# MySQL isn't found
if [[ $MYSQL == '' ]]; then

	# Some people have mysql installed via MacPorts, this will install it with an appending 5.
	MYSQL="$(which mysql5)"

fi

# No backup path given
if [[ $UPDATE_PATH == '' ]]; then
	UPDATE_PATH=backup.sql
fi

$MYSQL --default-character-set='utf8' --host="$db_host" --port="$db_port" --user="$db_user" --password="$db_pass" $db_name < $UPDATE_PATH;
