#! /bin/bash
#
# This script will remove all cache-files.
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

rm -f `find ../src/Install/Cache/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`

rm -f `find ../src/Frontend/Cache/CachedTemplates/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/Config/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/Locale/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/MinifiedCss/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/MinifiedJs/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/Navigation/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Frontend/Cache/CompiledTemplates/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`

rm -f `find ../src/Backend/Cache/Analytics/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Config/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Cronjobs/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Locale/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Mailmotor/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Navigation/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/CompiledTemplates/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`
rm -f `find ../src/Backend/Cache/Logs/ ! -name ".gitignore" -type f ! -path *.svn/* -type f`

rm -f ../app/config/parameters.yml

echo 'All done! Ready for reinstall.'
