#! /bin/bash
#
# This script will remove all cache-files.
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

rm -f `ls ../default_www/install/cache | grep -v ".gitignore"`
rm -f ../default_www/install/installed.txt

rm -f `ls ../default_www/frontend/cache/cached_templates | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/config | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/locale | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/minified_css | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/minified_js | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/navigation | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/statistics | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/compiled_templates | grep -v ".gitignore"`

rm -f `ls ../default_www/backend/cache/analytics | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/config | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/cronjobs | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/locale | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/mailmotor | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/compiled_templates | grep -v ".gitignore"`

rm -f ../library/globals.php
rm -f ../library/globals.frontend.php
rm -f ../library/globals.backend.php

echo 'All done! Cache files removed.'