#! /bin/bash
#
# This script will remove all cache-files.
#
# @version	1.1.0
# @author	Johan Ronsse <johan@netlash.com>
# @author	Tijs Verkoyen <tijs@sumocoders.be>

rm -f `ls ../default_www/install/cache | grep -v ".gitignore"`

rm -f `ls ../default_www/frontend/cache/cached_templates | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/locale | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/minified_css | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/minified_js | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/navigation | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/statistics | grep -v ".gitignore"`
rm -f `ls ../default_www/frontend/cache/compiled_templates | grep -v ".gitignore"`

rm -f `ls ../default_www/backend/cache/analytics | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/cronjobs | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/locale | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/mailmotor | grep -v ".gitignore"`
rm -f `ls ../default_www/backend/cache/compiled_templates | grep -v ".gitignore"`

echo 'All done! Cache files removed.'