services:
  mailmotor.validator.subscription:
    class: ForkCMS\Frontend\Modules\Mailmotor\Domain\Subscription\Validator\Constraints\EmailSubscriptionValidator
    calls:
      - [setSubscriber, ["@mailmotor.subscriber"]]
    tags:
      - { name: validator.constraint_validator }
  mailmotor.validator.unsubscription:
    class: ForkCMS\Frontend\Modules\Mailmotor\Domain\Subscription\Validator\Constraints\EmailUnsubscriptionValidator
    calls:
      - [setSubscriber, ["@mailmotor.subscriber"]]
    tags:
      - { name: validator.constraint_validator }
