imports:
  - { resource: commands.yml }

services:
    pages.copy:
        class: Backend\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocale
        tags:
            - { name: forkcms.copy_module_content_to_other_locale }
